pipeline:
  name: hello-node-api
  identifier: hellonodeapi
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Github
        repoName: hello-node-api
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          execution:
            steps:
              - step:
                  type: Run
                  name: npm install
                  identifier: npm_install
                  spec:
                    connectorRef: Docker_Container_registry
                    image: node:20-alpine
                    shell: Sh
                    command: npm ci
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_Container_registry
                    repo: mattthankachan
                    tags:
                      - latest
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: asdf
              namespace: ns-api
              automountServiceAccountToken: true
              nodeSelector: {}
              harnessImageConnectorRef: account.harnessImage
              os: Linux
